<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE paises [
<!ELEMENT paises (pais)>
<!ELEMENT pais (nombre*,continente,numero_hab,gobierno)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT continente (#PCDATA)>
<!ELEMENT numero_hab (#PCDATA)>
<!ELEMENT gobierno EMPTY>
]>
<paises>
    <pais>
        <nombre>Perú</nombre>
        <nombre>Virreinato del Perú</nombre>
        <continente>America</continente>
        <numero_hab>34000000</numero_hab>
        <gobierno/>
    </pais>
</paises>