<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
    <!ELEMENT root (origen,elaborado,nombre,provincia,prediccion)>
    <!ELEMENT origen (productor,web,enlace,language,copyright,nota_legal)>
    <!ELEMENT prediccion (dia*)>
    <!ELEMENT dia (prob_precipitacion*,cota_nieve_prov*,estado_cielo*,viento*,racha_max*,temperatura,sens_termica,humedad_relativa,uv_max?)>
    

    <!ATTLIST root id CDATA #REQUIRED>
    <!ATTLIST root version CDATA #REQUIRED> 
    <!ELEMENT productor (#PCDATA)>
    <!ELEMENT web (#PCDATA)>
    <!ELEMENT enlace (#PCDATA)>
    <!ELEMENT language (#PCDATA)>
    <!ELEMENT copyright (#PCDATA)>
    <!ELEMENT nota_legal (#PCDATA)>
    <!ELEMENT elaborado (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
        
    
    <!ATTLIST dia fecha CDATA #REQUIRED>

    <!ELEMENT prob_precipitacion ANY >
    <!ATTLIST prob_precipitacion periodo CDATA #IMPLIED>

    <!ELEMENT cota_nieve_prov ANY>
    <!ATTLIST cota_nieve_prov periodo CDATA #IMPLIED>

    <!ELEMENT estado_cielo  (#PCDATA)>
    <!ATTLIST estado_cielo periodo CDATA #IMPLIED>
    <!ATTLIST estado_cielo descripcion CDATA #IMPLIED>

    <!ELEMENT viento (direccion,velocidad)>
    <!ATTLIST viento periodo CDATA #IMPLIED>
    
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT velocidad (#PCDATA)>
    
    <!ELEMENT racha_max (#PCDATA)  >
    <!ATTLIST racha_max periodo CDATA #IMPLIED>

    <!ELEMENT temperatura (maxima,minima,dato*)>
    <!ELEMENT maxima (#PCDATA)>
    <!ELEMENT minima (#PCDATA)>
    <!ELEMENT dato (#PCDATA)>
    <!ATTLIST dato hora CDATA #REQUIRED>
    
    <!ELEMENT sens_termica (maxima,minima,dato*)>
    <!ELEMENT humedad_relativa (maxima,minima,dato*)>
    <!ELEMENT uv_max (#PCDATA) >

    

    
]>
<root id="12077" version="1.0">   
    <origen>
      <productor>Agencia Estatal de Meteorología - AEMET. Gobierno de España</productor>
      <web>https://www.aemet.es</web>
      <enlace>https://www.aemet.es/es/eltiempo/prediccion/municipios/moncofa-id12077</enlace>
      <language>es</language>
      <copyright>© AEMET. Autorizado el uso de la información y su reproducción citando a AEMET como autora de la misma.</copyright>
      <nota_legal>https://www.aemet.es/es/nota_legal</nota_legal>
    </origen>
    <elaborado>2024-02-17T13:58:08</elaborado>
    <nombre>Moncofa</nombre>
    <provincia>Castelló/Castellón</provincia>
    <prediccion>
      <dia fecha="2024-02-17">
        <prob_precipitacion periodo="00-24"/>
        <prob_precipitacion periodo="00-12"/>
        <prob_precipitacion periodo="12-24">0</prob_precipitacion>
        <prob_precipitacion periodo="00-06"/>
        <prob_precipitacion periodo="06-12">0</prob_precipitacion>
        <prob_precipitacion periodo="12-18">0</prob_precipitacion>
        <prob_precipitacion periodo="18-24">0</prob_precipitacion>
        <cota_nieve_prov periodo="00-24"/>
        <cota_nieve_prov periodo="00-12"/>
        <cota_nieve_prov periodo="12-24"/>
        <cota_nieve_prov periodo="00-06"/>
        <cota_nieve_prov periodo="06-12"/>
        <cota_nieve_prov periodo="12-18"/>
        <cota_nieve_prov periodo="18-24"/>
        <estado_cielo periodo="00-24" descripcion=""/>
        <estado_cielo periodo="00-12" descripcion=""/>
        <estado_cielo periodo="12-24" descripcion="Despejado">11</estado_cielo>
        <estado_cielo periodo="00-06" descripcion=""/>
        <estado_cielo periodo="06-12" descripcion="Poco nuboso">12</estado_cielo>
        <estado_cielo periodo="12-18" descripcion="Despejado">11</estado_cielo>
        <estado_cielo periodo="18-24" descripcion="Despejado">11n</estado_cielo>
        <viento periodo="00-24">
          <direccion/>
          <velocidad/>
        </viento>
        <viento periodo="00-12">
          <direccion/>
          <velocidad/>
        </viento>
        <viento periodo="12-24">
          <direccion>C</direccion>
          <velocidad>0</velocidad>
        </viento>
        <viento periodo="00-06">
          <direccion>C</direccion>
          <velocidad>0</velocidad>
        </viento>
        <viento periodo="06-12">
          <direccion>C</direccion>
          <velocidad>0</velocidad>
        </viento>
        <viento periodo="12-18">
          <direccion>C</direccion>
          <velocidad>0</velocidad>
        </viento>
        <viento periodo="18-24">
          <direccion>C</direccion>
          <velocidad>0</velocidad>
        </viento>
        <racha_max periodo="00-24"/>
        <racha_max periodo="00-12"/>
        <racha_max periodo="12-24"/>
        <racha_max periodo="00-06"/>
        <racha_max periodo="06-12"/>
        <racha_max periodo="12-18"/>
        <racha_max periodo="18-24"/>
        <temperatura>
          <maxima>18</maxima>
          <minima>10</minima>
          <dato hora="06">12</dato>
          <dato hora="12">17</dato>
          <dato hora="18">15</dato>
          <dato hora="24">11</dato>
        </temperatura>
        <sens_termica>
          <maxima>18</maxima>
          <minima>10</minima>
          <dato hora="06">12</dato>
          <dato hora="12">17</dato>
          <dato hora="18">15</dato>
          <dato hora="24">11</dato>
        </sens_termica>
        <humedad_relativa>
          <maxima>70</maxima>
          <minima>45</minima>
          <dato hora="06">55</dato>
          <dato hora="12">45</dato>
          <dato hora="18">60</dato>
          <dato hora="24">70</dato>
        </humedad_relativa>
        <uv_max>3</uv_max>
      </dia>
      <dia fecha="2024-02-18">
        <prob_precipitacion periodo="00-24">0</prob_precipitacion>
        <prob_precipitacion periodo="00-12">0</prob_precipitacion>
        <prob_precipitacion periodo="12-24">0</prob_precipitacion>
        <prob_precipitacion periodo="00-06">0</prob_precipitacion>
        <prob_precipitacion periodo="06-12">0</prob_precipitacion>
        <prob_precipitacion periodo="12-18">0</prob_precipitacion>
        <prob_precipitacion periodo="18-24">0</prob_precipitacion>
        <cota_nieve_prov periodo="00-24"/>
        <cota_nieve_prov periodo="00-12"/>
        <cota_nieve_prov periodo="12-24"/>
        <cota_nieve_prov periodo="00-06"/>
        <cota_nieve_prov periodo="06-12"/>
        <cota_nieve_prov periodo="12-18"/>
        <cota_nieve_prov periodo="18-24"/>
        <estado_cielo periodo="00-24" descripcion="Nubes altas">17</estado_cielo>
        <estado_cielo periodo="00-12" descripcion="Poco nuboso">12</estado_cielo>
        <estado_cielo periodo="12-24" descripcion="Nubes altas">17</estado_cielo>
        <estado_cielo periodo="00-06" descripcion="Poco nuboso">12n</estado_cielo>
        <estado_cielo periodo="06-12" descripcion="Poco nuboso">12</estado_cielo>
        <estado_cielo periodo="12-18" descripcion="Nubes altas">17</estado_cielo>
        <estado_cielo periodo="18-24" descripcion="Nubes altas">17n</estado_cielo>
        <viento periodo="00-24">
          <direccion>S</direccion>
          <velocidad>15</velocidad>
        </viento>
        <viento periodo="00-12">
          <direccion>S</direccion>
          <velocidad>15</velocidad>
        </viento>
        <viento periodo="12-24">
          <direccion>S</direccion>
          <velocidad>15</velocidad>
        </viento>
        <viento periodo="00-06">
          <direccion>C</direccion>
          <velocidad>0</velocidad>
        </viento>
        <viento periodo="06-12">
          <direccion>S</direccion>
          <velocidad>15</velocidad>
        </viento>
        <viento periodo="12-18">
          <direccion>S</direccion>
          <velocidad>5</velocidad>
        </viento>
        <viento periodo="18-24">
          <direccion>C</direccion>
          <velocidad>0</velocidad>
        </viento>
        <racha_max periodo="00-24"/>
        <racha_max periodo="00-12"/>
        <racha_max periodo="12-24"/>
        <racha_max periodo="00-06"/>
        <racha_max periodo="06-12"/>
        <racha_max periodo="12-18"/>
        <racha_max periodo="18-24"/>
        <temperatura>
          <maxima>18</maxima>
          <minima>8</minima>
          <dato hora="06">8</dato>
          <dato hora="12">17</dato>
          <dato hora="18">14</dato>
          <dato hora="24">11</dato>
        </temperatura>
        <sens_termica>
          <maxima>18</maxima>
          <minima>8</minima>
          <dato hora="06">8</dato>
          <dato hora="12">17</dato>
          <dato hora="18">14</dato>
          <dato hora="24">11</dato>
        </sens_termica>
        <humedad_relativa>
          <maxima>85</maxima>
          <minima>55</minima>
          <dato hora="06">80</dato>
          <dato hora="12">55</dato>
          <dato hora="18">75</dato>
          <dato hora="24">80</dato>
        </humedad_relativa>
        <uv_max>3</uv_max>
      </dia>
      <dia fecha="2024-02-19">
        <prob_precipitacion periodo="00-24">5</prob_precipitacion>
        <prob_precipitacion periodo="00-12">0</prob_precipitacion>
        <prob_precipitacion periodo="12-24">0</prob_precipitacion>
        <cota_nieve_prov periodo="00-24"/>
        <cota_nieve_prov periodo="00-12"/>
        <cota_nieve_prov periodo="12-24"/>
        <estado_cielo periodo="00-24" descripcion="Poco nuboso">12</estado_cielo>
        <estado_cielo periodo="00-12" descripcion="Poco nuboso">12</estado_cielo>
        <estado_cielo periodo="12-24" descripcion="Poco nuboso">12</estado_cielo>
        <viento periodo="00-24">
          <direccion>SE</direccion>
          <velocidad>10</velocidad>
        </viento>
        <viento periodo="00-12">
          <direccion>SE</direccion>
          <velocidad>10</velocidad>
        </viento>
        <viento periodo="12-24">
          <direccion>SE</direccion>
          <velocidad>10</velocidad>
        </viento>
        <racha_max periodo="00-24"/>
        <racha_max periodo="00-12"/>
        <racha_max periodo="12-24"/>
        <temperatura>
          <maxima>18</maxima>
          <minima>9</minima>
        </temperatura>
        <sens_termica>
          <maxima>18</maxima>
          <minima>9</minima>
        </sens_termica>
        <humedad_relativa>
          <maxima>85</maxima>
          <minima>60</minima>
        </humedad_relativa>
        <uv_max>3</uv_max>
      </dia>
      <dia fecha="2024-02-20">
        <prob_precipitacion periodo="00-24">0</prob_precipitacion>
        <prob_precipitacion periodo="00-12">0</prob_precipitacion>
        <prob_precipitacion periodo="12-24">0</prob_precipitacion>
        <cota_nieve_prov periodo="00-24"/>
        <cota_nieve_prov periodo="00-12"/>
        <cota_nieve_prov periodo="12-24"/>
        <estado_cielo periodo="00-24" descripcion="Poco nuboso">12</estado_cielo>
        <estado_cielo periodo="00-12" descripcion="Poco nuboso">12</estado_cielo>
        <estado_cielo periodo="12-24" descripcion="Poco nuboso">12</estado_cielo>
        <viento periodo="00-24">
          <direccion>E</direccion>
          <velocidad>10</velocidad>
        </viento>
        <viento periodo="00-12">
          <direccion>E</direccion>
          <velocidad>10</velocidad>
        </viento>
        <viento periodo="12-24">
          <direccion>E</direccion>
          <velocidad>10</velocidad>
        </viento>
        <racha_max periodo="00-24"/>
        <racha_max periodo="00-12"/>
        <racha_max periodo="12-24"/>
        <temperatura>
          <maxima>17</maxima>
          <minima>8</minima>
        </temperatura>
        <sens_termica>
          <maxima>17</maxima>
          <minima>8</minima>
        </sens_termica>
        <humedad_relativa>
          <maxima>95</maxima>
          <minima>45</minima>
        </humedad_relativa>
        <uv_max>3</uv_max>
      </dia>
      <dia fecha="2024-02-21">
        <prob_precipitacion>0</prob_precipitacion>
        <cota_nieve_prov/>
        <estado_cielo descripcion="Nubes altas">17</estado_cielo>
        <viento>
          <direccion>S</direccion>
          <velocidad>15</velocidad>
        </viento>
        <racha_max/>
        <temperatura>
          <maxima>17</maxima>
          <minima>7</minima>
        </temperatura>
        <sens_termica>
          <maxima>17</maxima>
          <minima>7</minima>
        </sens_termica>
        <humedad_relativa>
          <maxima>95</maxima>
          <minima>55</minima>
        </humedad_relativa>
        <uv_max>3</uv_max>
      </dia>
      <dia fecha="2024-02-22">
        <prob_precipitacion>45</prob_precipitacion>
        <cota_nieve_prov>1700</cota_nieve_prov>
        <estado_cielo descripcion="Intervalos nubosos">13</estado_cielo>
        <viento>
          <direccion>E</direccion>
          <velocidad>15</velocidad>
        </viento>
        <racha_max/>
        <temperatura>
          <maxima>24</maxima>
          <minima>8</minima>
        </temperatura>
        <sens_termica>
          <maxima>24</maxima>
          <minima>8</minima>
        </sens_termica>
        <humedad_relativa>
          <maxima>75</maxima>
          <minima>35</minima>
        </humedad_relativa>
      </dia>
      <dia fecha="2024-02-23">
        <prob_precipitacion>45</prob_precipitacion>
        <cota_nieve_prov>800</cota_nieve_prov>
        <estado_cielo descripcion="Intervalos nubosos">13</estado_cielo>
        <viento>
          <direccion>O</direccion>
          <velocidad>30</velocidad>
        </viento>
        <racha_max>55</racha_max>
        <temperatura>
          <maxima>19</maxima>
          <minima>11</minima>
        </temperatura>
        <sens_termica>
          <maxima>19</maxima>
          <minima>11</minima>
        </sens_termica>
        <humedad_relativa>
          <maxima>60</maxima>
          <minima>25</minima>
        </humedad_relativa>
      </dia>
    </prediccion>
  </root>